
version: '3.5'

services:

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - type: bind
        source: ./db
        target: /data/db

  feeder:
    build: ./feeder
    restart: always
    volumes:
      - type: bind
        source: ./ids
        target: /usr/src/app/channel_ids

  downloader:
    build: ./downloader
    volumes:
      - type: bind
        source: ./videos
        target: /usr/src/app/videos
      - type: bind
        source: ./transcripts
        target: /usr/src/app/transcripts


  transcriber:
    build: ./transcriber
    volumes:
      - type: bind
        source: ./videos
        target: /usr/src/app/videos

  pipeline:
    build: ./pipeline

  vector:
    build: ./vector
    ports:
      - 8000:8000
    volumes:
      - type: bind
        source: ./transcripts
        target: /usr/src/app/transcripts
  
  frontend:
    build:
      context: ./frontend/
    command: serve -s build
    volumes:
      - ./frontend/:/usr/app
      - /usr/app/node_modules
    ports:
      - 5000:5000
